
auth.token=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

defaults.org=megatron-logistic
defaults.project=chauffer

defaults.url=https://sentry.io/
